spring:
  application:
    name: weather-api

weather:
  api:
    key: ADD_YOUR_API_KEY_HERE

#logging:
#  level:
#    org.springframework: DEBUG

resilience4j.ratelimiter:
  instances:
    todays-weather:
      limitForPeriod: 4
      limitRefreshPeriod: 2s
      timeoutDuration: 500ns

    weather-range:
      limitForPeriod: 4
      limitRefreshPeriod: 2s
      timeoutDuration: 500ns